# Generated by Django 5.1.6 on 2025-03-11 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_nickname_user_firstname_user_lastname'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='max_xp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='level',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.level'),
        ),
    ]
