# Generated by Django 5.1.6 on 2025-02-28 11:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('syllabus', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('credits', models.IntegerField()),
                ('mattter', models.CharField(choices=[('Histoire', 'histoire'), ('Geographie', 'geographie'), ('Francais', 'francais'), ('Mathematique', 'mathematique')], default='francais', max_length=50)),
                ('min_level_required', models.IntegerField(default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CourseProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress_percentage', models.IntegerField(default=0)),
                ('last_accessed', models.DateTimeField(default=django.utils.timezone.now)),
                ('grade', models.FloatField(default=0.0)),
                ('completion_status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CourseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('mattter', models.CharField(choices=[('Histoire', 'histoire'), ('Geographie', 'geographie'), ('Francais', 'francais'), ('Mathematique', 'mathematique')], default='francais', max_length=50)),
                ('syllabus', models.FileField(upload_to='syllabus/')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('credits', models.IntegerField(default=1)),
                ('min_level_required', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('progessPercentage', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
