# Generated by Django 5.1.6 on 2025-03-01 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
        ('users', '0002_remove_level_id_alter_level_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseprogress',
            name='user',
        ),
        migrations.AddField(
            model_name='courseprogress',
            name='student',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, to='users.student'),
            preserve_default=False,
        ),
    ]
