# Generated by Django 5.1.6 on 2025-03-11 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_course_credits'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='mattter',
            new_name='matter',
        ),
    ]
