# Generated by Django 5.1.6 on 2025-03-14 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_matter_remove_course_created_from_request_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='matter',
        ),
    ]
