# Generated by Django 5.1.6 on 2025-03-14 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_remove_course_matter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matter',
            name='id',
        ),
        migrations.AlterField(
            model_name='matter',
            name='name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
