# Generated by Django 5.1.6 on 2025-03-14 01:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_remove_matter_id_alter_matter_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='matter',
            field=models.ForeignKey(default='Mathématiques', on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='courses.matter'),
        ),
    ]
