# Generated by Django 5.1.6 on 2025-03-15 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_course_matter'),
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='quizresult',
            unique_together={('progress', 'quiz')},
        ),
    ]
