# Generated by Django 5.1.6 on 2025-02-28 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='courses.course')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('resource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='resources.resource')),
                ('file', models.FileField(upload_to='resources/audios/')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('resources.resource',),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('resource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='resources.resource')),
                ('file', models.FileField(upload_to='resources/documents/')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('resources.resource',),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('resource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='resources.resource')),
                ('resolution', models.CharField(max_length=50)),
                ('file', models.ImageField(upload_to='resources/images/')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('resources.resource',),
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('resource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='resources.resource')),
                ('duration', models.DurationField()),
                ('file', models.FileField(upload_to='resources/videos/')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('resources.resource',),
        ),
    ]
