# Generated by Django 5.1.6 on 2025-02-28 11:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('badges', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='badge',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='badges', to='users.student'),
        ),
    ]
